#!/bin/bash

set -x
set -e
set -o pipefail

REPO=${REPO:=MetaCubeX/Clash.Meta}

CURL=${CURL:=curl}
JQ=${JQ:=jq}

VERSION=${VERSION:=$(${CURL} -s https://api.github.com/repos/${REPO}/releases/latest | jq -r .tag_name)}

ARCH=${ARCH:=amd64}

OUTPUT=${OUTPUT:=clash-meta}

curl -LJ "https://github.com/${REPO}/releases/latest/download/clash.meta-linux-${ARCH}-${VERSION}.gz" | gunzip > ${OUTPUT}
